version: '3.7'

services:
  backend:
    build: .
    command: flask run -h 0.0.0.0 -p 5000
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
    depends_on:
      - redis
    volumes:
      - .:/app
    ports:
      - "5000:5000"
#    env_file:
#      - ./web.env

  worker:
    build: .
    command: celery -A app.tasks worker --loglevel=INFO --concurrency=1 -Q tasks --max-tasks-per-child=5  --prefetch-multiplier=1
    depends_on:
      - redis
    volumes:
      - .:/app

  flower:
    image: mher/flower
    links:
      - redis
    depends_on:
      - redis
    command: ["flower", "--broker=redis://redis:6379/0", '--address=0.0.0.0']
    ports:
      - 5555:5555


  redis:
    image: redis:5-alpine
