version: '3.3'

services:
  backend:
    build: .
    command: python server.py
#    depends_on:
#      - db
#      - redis
    volumes:
      - .:/app
    ports:
      - "8000:8000"
#    env_file:
#      - ./web.env

#  db:
#    image: postgres:11-alpine
#    environment:
#      - POSTGRES_DB=test
#      - POSTGRES_USER=test
#      - POSTGRES_PASSWORD=test
#
#  redis:
#    image: redis:5-alpine
