version: '3.3'

services:
  backend:
    build: .
    command: flask run -h 0.0.0.0 -p 5000
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
    depends_on:
#      - db
      - redis
    volumes:
      - .:/app
    ports:
      - "5000:5000"
#    env_file:
#      - ./web.env

#  db:
#    image: postgres:11-alpine
#    environment:
#      - POSTGRES_DB=test
#      - POSTGRES_USER=test
#      - POSTGRES_PASSWORD=test
#
  redis:
    image: redis:5-alpine
