apiVersion: apps/v1
kind: Deployment
metadata:
  name: orionshah-redis
spec:
  selector:
    matchLabels:
      app: orionshah-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: orionshah-redis
    spec:
      nodeSelector:
        env: apps
      containers:
      - name: orionshah-redis
        image: redis:5-alpine
        ports:
          containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: orionshah-redis
  labels:
    app: orionshah-redis
spec:
  ports:
    - port: 6379
      name: redis
  selector:
    app: orionshah-redis
